name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Install dependencies
      run: dotnet restore ChatService.Client/ChatService.Client.csproj
           dotnet restore ChatService.Datacontracts/ChatService.Datacontracts.csproj
           dotnet restore ChatService.DeploymentTests/ChatService.DeploymentTests.csproj
           dotnet restore ChatService.IntegrationTests/ChatService.IntegrationTests.csproj
           dotnet restore ChatService.Web/ChatService.Web.csproj
           dotnet restore ChatService.Tests/ChatService.Tests.csproj
    - name: Build
      run: dotnet build **/*.csproj --configuration Release --no-restore
